SET SEARCH_PATH TO E_COMMERCE, E_COMMERCWE; 


-- VAILIDATING  NEW CUSTOMER CURRENT  VS  LAST YEAR

WITH MAX_DATE_CTE AS 
( SELECT MAX(PURCHASE_DATE) AS MAX_DATE
FROM FACT_SALES
),

FIRST_PURCHASE AS (
SELECT CUSTOMER_UNIQUE_ID, MIN(PURCHASE_DATE) AS FIRST_PURCHASE_DATE
FROM FACT_SALES
WHERE ORDER_STATUS IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
GROUP BY CUSTOMER_UNIQUE_ID
),

CUST AS
(SELECT
COUNT (*) FILTER(
WHERE FIRST_PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND FIRST_PURCHASE_DATE <= M.MAX_DATE
) AS NEW_CUST,

COUNT (*) FILTER(
WHERE FIRST_PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) - INTERVAL '1 YEAR'
AND FIRST_PURCHASE_DATE < DATE_TRUNC('YEAR', M.MAX_DATE)
) AS PREV_CUSTOMER

FROM FIRST_PURCHASE FP
CROSS JOIN MAX_DATE_CTE M
)
SELECT 
ROUND(((NEW_CUST - PREV_CUSTOMER):: NUMERIC / NULLIF(PREV_CUSTOMER,0)) * 100, 2)
AS GROWTH,
NEW_CUST,
PREV_CUSTOMER
FROM CUST;


--- VAILIDATING  REPEATED  CUSTOMER 

WITH MAX_DATE_CTE AS (
SELECT MAX(PURCHASE_DATE) AS MAX_DATE
FROM FACT_SALES),

FIRST_PURCHASE AS
(
SELECT CUSTOMER_UNIQUE_ID, MIN(PURCHASE_DATE) AS FIRST_PURCHASE_DATE
FROM FACT_SALES
 WHERE ORDER_STATUS IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
GROUP BY CUSTOMER_UNIQUE_ID
),

REPEATED AS 
(
SELECT
COUNT(DISTINCT FS.CUSTOMER_UNIQUE_ID) FILTER
(
WHERE FP.FIRST_PURCHASE_DATE < DATE_TRUNC('YEAR', M.MAX_DATE)
AND FS.PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND FS.PURCHASE_DATE <= M.MAX_DATE
) AS CURRENT_YEAR,


COUNT(DISTINCT FS.CUSTOMER_UNIQUE_ID) FILTER
(
WHERE FP.FIRST_PURCHASE_DATE < DATE_TRUNC('YEAR', M.MAX_DATE) -INTERVAL '1 YEAR'
AND FS.PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) -INTERVAL '1 YEAR'
AND FS.PURCHASE_DATE <=  DATE_TRUNC('YEAR', M.MAX_DATE)
) AS LAST_YEAR

FROM FACT_SALES FS
CROSS JOIN MAX_DATE_CTE M
JOIN FIRST_PURCHASE FP
ON FS.CUSTOMER_UNIQUE_ID = FP.CUSTOMER_UNIQUE_ID

 WHERE FS.ORDER_STATUS IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
)

SELECT 
CURRENT_YEAR,
LAST_YEAR,
ROUND(((CURRENT_YEAR - LAST_YEAR)::NUMERIC / NULLIF(LAST_YEAR,0)) * 100, 2)
AS GROWTH
FROM REPEATED;


--- VAILIDATING  CLV 

WITH ITEM_SOLD  AS 
(SELECT 
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
SUM(TOTAL_REVENUE) /
COUNT(DISTINCT CUSTOMER_UNIQUE_ID) AS CLV
FROM FACT_SALES 
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
GROUP BY  YEAR_NO
)
SELECT * FROM ITEM_SOLD
WHERE YEAR_NO = '2018'


-- VALIDATING  REVENUE BY NEW CUSTOMER

WITH MAX_DATE_CTE AS 
( SELECT MAX(PURCHASE_DATE) AS MAX_DATE FROM FACT_SALES
),

FIRST_PURCHASE AS(
SELECT CUSTOMER_UNIQUE_ID, MIN(PURCHASE_DATE) AS FIRST_PURCHASE_DATE
FROM FACT_SALES
WHERE order_status IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
GROUP BY CUSTOMER_UNIQUE_ID
),

REVENUE AS (
SELECT 
SUM(FS.TOTAL_REVENUE) FILTER
(
WHERE FP.FIRST_PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND  FP.FIRST_PURCHASE_DATE <= M.MAX_DATE 
) AS CURRENT_YEAR,

SUM(FS.TOTAL_REVENUE) FILTER
(
WHERE FP.FIRST_PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) - INTERVAL '1 YEAR'
AND  FP.FIRST_PURCHASE_DATE <=  DATE_TRUNC('YEAR', M.MAX_DATE)
) AS PREV_YEAR 

FROM FACT_SALES FS

JOIN FIRST_PURCHASE FP
ON FP.CUSTOMER_UNIQUE_ID = FS.CUSTOMER_UNIQUE_ID

CROSS JOIN MAX_DATE_CTE M

 WHERE fs.order_status IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
)
SELECT 
CURRENT_YEAR,
PREV_YEAR
FROM REVENUE

-- NEW AND REPEATEDX CUSTOMER BY  MONTH 

WITH FIRST_PURCHASE AS 
(
SELECT CUSTOMER_UNIQUE_ID, MIN(PURCHASE_DATE) AS FIRST_PURCHASE_DATE
FROM FACT_SALES

 GROUP BY CUSTOMER_UNIQUE_ID
),
COUNT_CUST AS (
SELECT 
EXTRACT(YEAR FROM FIRST_PURCHASE_DATE) AS YEAR,
EXTRACT(MONTH FROM FIRST_PURCHASE_DATE) AS MONTH_NO,
TO_CHAR(FIRST_PURCHASE_DATE, 'MON') AS MONTH,
COUNT(CUSTOMER_UNIQUE_ID) AS NEW_CUSTOMER,

LAG
(
COUNT(CUSTOMER_UNIQUE_ID)
)
OVER
(
ORDER BY
EXTRACT(YEAR FROM FIRST_PURCHASE_DATE), 
EXTRACT(MONTH FROM FIRST_PURCHASE_DATE)
)

FROM FIRST_PURCHASE
GROUP BY 
YEAR,
MONTH_NO,
MONTH

ORDER BY
YEAR,
MONTH_NO)
SELECT * FROM COUNT_CUST
WHERE YEAR = '2018'




WITH MAX_DATE_CTE AS
(
    SELECT MAX(PURCHASE_DATE) AS MAX_DATE
    FROM FACT_SALES
),

CUSTOMER_REVENUE AS
(
    SELECT
        CUSTOMER_UNIQUE_ID,
        SUM(TOTAL_REVENUE) AS CUSTOMER_REVENUE
    FROM FACT_SALES
    CROSS JOIN MAX_DATE_CTE M
    WHERE ORDER_STATUS IN
    (
        'Approved',
        'Delivered',
        'Invoiced',
        'Processing',
        'Shipped',
        'Unavailable'
    )
    AND PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
    AND PURCHASE_DATE <= M.MAX_DATE
    GROUP BY CUSTOMER_UNIQUE_ID
),

AVG_REVENUE AS
(
    SELECT AVG(CUSTOMER_REVENUE) AS AVG_CUSTOMER_REVENUE
    FROM CUSTOMER_REVENUE
),

CUSTOMER_SEGMENT AS
(
    SELECT
        CUSTOMER_UNIQUE_ID,
        CUSTOMER_REVENUE,
        CASE
            WHEN CUSTOMER_REVENUE >= AVG_CUSTOMER_REVENUE * 2 THEN 'HIGH VALUE'
            WHEN CUSTOMER_REVENUE >= AVG_CUSTOMER_REVENUE THEN 'MEDIUM VALUE'
            ELSE 'LOW VALUE'
        END AS CUSTOMER_SEGMENT
    FROM CUSTOMER_REVENUE
    CROSS JOIN AVG_REVENUE
)

SELECT
    CUSTOMER_SEGMENT,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) AS DISTINCT_CUSTOMER_COUNT,
    ROUND(SUM(CUSTOMER_REVENUE)::NUMERIC, 2) AS TOTAL_REVENUE
FROM CUSTOMER_SEGMENT
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_REVENUE DESC;










