SET SEARCH_PATH TO E_COMMERCE, E_COMMERCE

CREATE SCHEMA E_COMMERCE;


-- CREATING TABLES

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID TEXT PRIMARY KEY,
     CUSTOMER_UNIQUE_ID TEXT,
    CUSTOMER_ZIP_CODE_PREFIX TEXT,
    CUSTOMER_CITY TEXT,
    CUSTOMER_STATE TEXT
);


CREATE TABLE GEOLOCATION (
    GEOLOCATION_ZIP_CODE_PREFIX TEXT,
    GEOLOCATION_LAT NUMERIC,
    GEOLOCATION_LNG NUMERIC,
    GEOLOCATION_CITY TEXT,
   GEOLOCATION_STATE TEXT
);


CREATE TABLE PRODUCTS (
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_CATEGORY_NAME TEXT,
   PRODUCT_NAME_LENGTH INTEGER,
    PRODUCT_DESCRIPTION_LENGTH INTEGER,
    PRODUCT_PHOTOS_QTY INTEGER,
    PRODUCT_WEIGHT_G INTEGER,
    PRODUCT_LENGTH_CM INTEGER,
    PRODUCT_HEIGHT_CM INTEGER,
    PRODUCT_WIDTH_CM INTEGER
);


CREATE TABLE SELLERS (
   SELLER_ID TEXT PRIMARY KEY,
    SELLER_ZIP_CODE_PREFIX TEXT,
    SELLER_CITY TEXT,
   SELLER_STATE TEXT
);

CREATE TABLE ORDERS (
    ORDER_ID TEXT PRIMARY KEY,
    CUSTOMER_ID TEXT,
    ORDER_STATUS TEXT,
    ORDER_PURCHASE_TIMESTAMP TIMESTAMP,
    ORDER_APPROVED_AT TIMESTAMP,
	ORDER_DELIVERED_CARRIER_DATE TIMESTAMP,
    ORDER_DELIVERED_CUSTOMER_DATE TIMESTAMP,
    ORDER_ESTIMATED_DELIVERY_DATE TIMESTAMP
);

CREATE TABLE ORDERS_ITEMS (
    ORDER_ID TEXT,
    ORDER_ITEM_ID INTEGER,
    PRODUCT_ID TEXT,
    SELLER_ID TEXT,
    SHIPPING_LIMIT_DATE TIMESTAMP,
    PRICE NUMERIC,
    FREIGHT_VALUE NUMERIC
);


CREATE TABLE PAYMENTS (
   ORDER_ID TEXT,
   PAYMENT_SEQUENTIAL INTEGER,
   PAYMENT_TYPE TEXT,
   PAYMENT_INSTALLMENTS INTEGER,
   PAYMENT_VALUE NUMERIC
);

CREATE TABLE REVIEWS (
    REVIEW_ID TEXT,
    ORDER_ID TEXT,
    REVIEW_SCORE INTEGER,
    REVIEW_COMMENT_TITTLE TEXT,
    REVIEW_COMMENT_MESSAGE TEXT,
    REVIEW_CREATION_DATE TIMESTAMP,
    REVIEW_ANSWER_TIMESTAMP TIMESTAMP
);


CREATE TABLE CATEGORY (
    PRODUCT_CATEGORY_NAME TEXT PRIMARY KEY,
    PRODUCT_CATEGORY_NAME_ENGLISH TEXT
);


-- ESTABLISHING KEY RELATIONSHIP BETWEEN TABLES

ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS                                                   --LINKING ORDERS TO CUSTOMER TABLE
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);  


ALTER TABLE ORDERS_ITEMS
ADD  KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
ADD CONSCONSTRAINT FK_ITEMS_ORDERS
FOREIGNTRAINT FK_ITEMS_PRODUCT
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),                   --LINKING ORDER_ITEMS TO ORDER, PRODUCTS, SELLER TABLES
ADD CONSTRAINT FK_ITEMS_SELLER
FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(SELLER_ID);


ALTER TABLE PAYMENTS
ADD CONSTRAINT FK_PAYMENTS_ORDERS
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);                         --LINKING PAYMENTS TO ORDERS TABLE

ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_ORDER
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);                         --LINKING REVIEWS  TO ORDER TABLE


SELECT * FROM ORDERS_ITEMS
SELECT * FROM CATEGORY
SELECT * FROM GEOLOCATION
SELECT * FROM PAYMENTS                     
SELECT * FROM PRODUCTS                                                       -- TO CHECK DATA SUCESSFULLY IMPORTED 
SELECT * FROM REVIEWS
SELECT * FROM SELLERS
SELECT * FROM ORDERS`
SELECT * FROM CUSTOMERS



-- DATA CLEANING  

-- CLEANING CATEGORY TABLE 

SELECT * FROM CATEGORY

ALTER TABLE CATEGORY
RENAME COLUMN PRODUCT_CATEGORY_NAME_ENGLISH TO PRODUCT_CATEGORY;

UPDATE CATEGORY 
SET PRODUCT_CATEGORY = INITCAP(PRODUCT_CATEGORY) 

UPDATE CATEGORY SET CATEGORY_GROUP = 'Home & Living' WHERE PRODUCT_CATEGORY IN('bed_bath_table', 'furniture_decor', 'housewares', 'home_confort',
'home_comfort_2', 'furniture_living_room', 'furniture_bedroom','furniture_mattress_and_upholstery', 'kitchen_dining_laundry_garden_furniture',
'home_appliances', 'home_appliances_2', 'small_appliances', 'small_appliances_home_oven_and_coffee', 'la_cuisine',
'garden_tools', 'flowers', 'costruction_tools_garden');

UPDATE CATEGORY SET CATEGORY_GROUP = 'Electronics & Tech' WHERE PRODUCT_CATEGORY IN('computers_accessories', 'computers', 'electronics', 'telephony',
'fixed_telephony', 'tablets_printing_image', 'pc_gamer','consoles_games', 'audio', 'dvds_blu_ray', 'cds_dvds_musicals',
'cine_photo', 'air_conditioning', 'signaling_and_security')

UPDATE CATEGORY SET CATEGORY_GROUP = 'Fashion & Beauty' WHERE PRODUCT_CATEGORY IN('health_beauty', 'perfumery', 'fashion_bags_accessories',
'fashion_shoes', 'fashion_male_clothing', 'fashion_female_clothing','fashion_underwear_beach', 'fashion_sport', 'fashio_female_clothing',
'fashion_childrens_clothes', 'luggage_accessories', 'watches_gifts')

UPDATE CATEGORY SET CATEGORY_GROUP = 'Leisure & Hobbies' WHERE PRODUCT_CATEGORY IN('sports_leisure', 'toys', 'cool_stuff', 'party_supplies',
'christmas_supplies', 'art', 'arts_and_craftmanship','musical_instruments', 'books_general_interest',
'books_technical', 'books_imported', 'market_place')

UPDATE CATEGORY SET CATEGORY_GROUP = 'Auto & Tools' WHERE PRODUCT_CATEGORY IN('auto', 'construction_tools_construction', 'construction_tools_lights',
'construction_tools_safety', 'costruction_tools_tools','home_construction', 'industry_commerce_and_business','agro_industry_and_commerce')

UPDATE CATEGORY SET CATEGORY_GROUP = 'Baby, Kids & Pets' WHERE PRODUCT_CATEGORY IN('baby', 'diapers_and_hygiene', 'pet_shop')

UPDATE CATEGORY SET CATEGORY_GROUP = 'Food, Drinks & Offic' WHERE PRODUCT_CATEGORY IN('food', 'food_drink', 'drinks', 'office_furniture', 'stationery',
'security_and_services')

-- CLEANING CUSTOMER TABLE 

SELECT * FROM CUSTOMERS

UPDATE CUSTOMERS 
SET CUSTOMER_CITY = INITCAP(CUSTOMER_CITY) 


-- CLEANING ORDERS

SELECT * FROM ORDERS

SELECT DISTINCT ORDER_STATUS FROM ORDERS

UPDATE ORDERS
SET ORDER_STATUS = INITCAP(ORDER_STATUS)

SELECT * FROM ORDERS
WHERE ORDER_DELIVERED_CARRIER_DATE IS NULL

ALTER TABLE ORDERS
ALTER COLUMN ORDER_PURCHASE_TIMESTAMP TYPE DATE
USING ORDER_PURCHASE_TIMESTAMP::DATE

ALTER TABLE ORDERS
ALTER COLUMN ORDER_APPROVED_AT TYPE DATE
USING ORDER_APPROVED_AT::DATE

ALTER TABLE ORDERS
ALTER COLUMN ORDER_DELIVERED_CARRIER_DATE TYPE DATE
USING ORDER_DELIVERED_CARRIER_DATE::DATE

ALTER TABLE ORDERS
ALTER COLUMN ORDER_DELIVERED_CUSTOMER_DATE TYPE DATE
USING ORDER_DELIVERED_CUSTOMER_DATE::DATE

ALTER TABLE ORDERS
ALTER COLUMN ORDER_ESTIMATED_DELIVERY_DATE TYPE DATE
USING ORDER_ESTIMATED_DELIVERY_DATE::DATE

-- CLEANING ODERS_ITEMS

SELECT * FROM ORDERS_ITEMS


ALTER TABLE ORDERS_ITEMS
ALTER COLUMN SHIPPING_LIMIT_DATE TYPE DATE
USING SHIPPING_LIMIT_DATE::DATE

WITH PO AS 
(SELECT *,
ROW_NUMBER() OVER (PARTITION BY ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_DATE, PRICE, FREIGHT_VALUE) AS ROW
FROM ORDERS_ITEMS)
SELECT * FROM PO
WHERE ROW = 1

-- CLEANING PAYMENTS

SELECT * FROM PAYMENTS

UPDATE PAYMENTS
SET PAYMENT_TYPE = INITCAP(PAYMENT_TYPE)

-- CLEANING SELLER

SELECT * FROM SELLERS

UPDATE SELLERS
SET SELLER_CITY = INITCAP(SELLER_CITY)


-- FILLING NULL VALUES FOR PRODUCTS 

UPDATE PRODUCTS
SET PRODUCT_CATEGORY_NAME = COALESCE(PRODUCT_CATEGORY_NAME, 'N/A')

--CREATING INDEXING FOR FASTER DATA RETRIVAL


CREATE INDEX IN_ORDER_ID ON ORDERS(ORDER_ID);
CREATE INDEX IN_ORDER_CUSTOMER_ID ON ORDERS(CUSTOMER_ID);                    --FOR ORDERS TABLE 
CREATE INDEX IN_ORDER_PUSRCHASE_DATE ON ORDERS(ORDER_PURCHASE_TIMESTAMP);


CREATE INDEX IN_ITEMS_ORDER_ID ON ORDERS_ITEMS(ORDER_ID);
CREATE INDEX IN_ITEMS_PRODUCT_ID ON ORDERS_ITEMS(PRODUCT_ID);                --FOR ORDERS_ITEMS TABLE
CREATE INDEX IN_ITEMS_SELLER_ID ON ORDERS_ITEMS(SELLER_ID);


CREATE INDEX IN_CUSTOMER_CUSTOMER_ID ON CUSTOMERS(CUSTOMER_ID);
CREATE INDEX IN_CUSTOMER_STATE ON CUSTOMERS(CUSTOMER_SATE);                  --FOR CUSTOMERS TABLE

CREATE INDEX IN_PAYMENTS_ORDER_ID ON PAYMENTS(ORDER_ID);                     --FOR PAYMENTS TABLE

CREATE INDEX IN_REVIEWS_ORDER_ID ON REVIEWS(ORDER_ID);                       --FOR REVIEWS TABLE



-- CREATING VIEWS TO RETURN MULLTIPLE COLUMNS AS ONE AND TO AVOID UNNECESSARY COLUMN
SELECT * FROM ORDERS_ITEMS

CREATE VIEW FACT_ORDERS_ITEMS AS
SELECT
OI.ORDER_ID,  OI.PRODUCT_ID, OI.SHIPPING_LIMIT_DATE, OI.SELLER_ID,
SUM(OI.PRICE) AS TOTAL_REVENUE,
SUM(OI.FREIGHT_VALUE) AS FREIGHT_CHARGE,
MAX(OI.ORDER_ITEM_ID) AS TOTAL_ITEMS,
SUM(OI.PRICE + OI.FREIGHT_VALUE) AS TOTAL_PAYMENT
FROM ORDERS_ITEMS OI
GROUP BY OI.ORDER_ID, OI.PRODUCT_ID, OI.SHIPPING_LIMIT_DATE,  SELLER_ID

CREATE VIEW DIM_PRODUCT AS 
SELECT P.PRODUCT_ID, T.PRODUCT_CATEGORY,  T.CATEGORY_GROUP,
P.PRODUCT_WEIGHT_G, P.PRODUCT_LENGTH_CM, P.PRODUCT_HEIGHT_CM, P.PRODUCT_WIDTH_CM,
(P.PRODUCT_LENGTH_CM * P.PRODUCT_HEIGHT_CM * P.PRODUCT_WIDTH_CM ) AS VOLUME
FROM PRODUCTS P
LEFT JOIN CATEGORY T
ON T.PRODUCT_CATEGORY_NAME = P.PRODUCT_CATEGORY_NAME;

CREATE VIEW ORDERS_PAYMENT AS
SELECT
OP.ORDER_ID,
MAX(OP.PAYMENT_INSTALLMENTS) AS ORDERS_PAYMENT_INSTALLMENTS,
(ARRAY_AGG(OP.PAYMENT_TYPE ORDER BY OP.PAYMENT_VALUE DESC NULLS LAST))[1] AS ORDER_PAYMENT_TYPE
FROM PAYMENTS OP
GROUP BY OP.ORDER_ID; 



CREATE VIEW FACT_REVIEW AS 
SELECT DISTINCT ON (ORDER_ID)
ORDER_ID,
REVIEW_SCORE,
REVIEW_ID
FROM REVIEWS
ORDER BY ORDER_ID, REVIEW_CREATION_DATE DESC NULLS LAST;


CREATE VIEW FACT_ORDERS AS
SELECT
O.ORDER_ID,
O.CUSTOMER_ID,
C.CUSTOMER_UNIQUE_ID,
O.ORDER_STATUS,
O.ORDER_PURCHASE_TIMESTAMP AS PURCHASE_DATE,
O.ORDER_DELIVERED_CUSTOMER_DATE AS DELIVERED_DATE,
O.ORDER_ESTIMATED_DELIVERY_DATE AS ESTIMATED_DATE,
C.CUSTOMER_CITY,
C.CUSTOMER_STATE
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID

CREATE VIEW FACT_SALES AS
SELECT 
OI.ORDER_ID,
OI.PRODUCT_ID,
OI.SELLER_ID,
O.CUSTOMER_UNIQUE_ID,
COALESCE(C.CATEGORY_GROUP,'N/A') AS CATEGORY_GROUP,
OI.SHIPPING_LIMIT_DATE,
OI.TOTAL_REVENUE,
OI.FREIGHT_CHARGE,
P.ORDER_PAYMENT_TYPE,
P.ORDERS_PAYMENT_INSTALLMENTS,
O.ORDER_STATUS,
O.PURCHASE_DATE,
O.DELIVERED_DATE,
O.ESTIMATED_DATE,
(O.ESTIMATED_DATE - O.DELIVERED_DATE) AS TOTAL_DAYS,
O.CUSTOMER_CITY,
O.CUSTOMER_STATE,
S.SELLER_CITY,
S.SELLER_STATE,
R.REVIEW_SCORE
FROM FACT_ORDERS_ITEMS OI
JOIN FACT_ORDERS O ON O.ORDER_ID = OI.ORDER_ID 
JOIN ORDERS_PAYMENT P ON OI.ORDER_ID = P.ORDER_ID
JOIN SELLERS S ON OI.SELLER_ID = S.SELLER_ID
JOIN REVIEWS R ON OI.ORDER_ID = R.ORDER_ID 
JOIN DIM_PRODUCT C ON OI.PRODUCT_ID = C.PRODUCT_ID


CREATE VIEW FACT_SALES1 AS
SELECT 
OI.ORDER_ID,
OI.PRODUCT_ID,
OI.SELLER_ID,
O.CUSTOMER_UNIQUE_ID,
COALESCE(C.CATEGORY_GROUP,'N/A') AS CATEGORY_GROUP,
OI.SHIPPING_LIMIT_DATE,
OI.TOTAL_REVENUE,
OI.FREIGHT_CHARGE,
P.ORDER_PAYMENT_TYPE,
P.ORDERS_PAYMENT_INSTALLMENTS,
O.ORDER_STATUS,
O.PURCHASE_DATE,
O.DELIVERED_DATE,
O.ESTIMATED_DATE,
(O.ESTIMATED_DATE - O.DELIVERED_DATE) AS TOTAL_DAYS,
O.CUSTOMER_CITY,
O.CUSTOMER_STATE,
S.SELLER_CITY,
S.SELLER_STATE,
R.REVIEW_SCORE
FROM FACT_ORDERS_ITEMS OI
JOIN FACT_ORDERS O ON O.ORDER_ID = OI.ORDER_ID 
JOIN ORDERS_PAYMENT P ON OI.ORDER_ID = P.ORDER_ID
JOIN SELLERS S ON OI.SELLER_ID = S.SELLER_ID
JOIN REVIEWS R ON OI.ORDER_ID = R.ORDER_ID 
JOIN DIM_PRODUCT C ON OI.PRODUCT_ID = C.PRODUCT_ID

SELECT * FROM FACT_SALES

SELECT COUNT(*) as total_repeat_customers
FROM (
    SELECT customer_unique_id
    FROM FACT_SALES
    GROUP BY customer_unique_id
    HAVING COUNT(*) > 1
) as repeat_customers;



SELECT
    purchase_date,
    SUM(total_revenue) OVER (
        ORDER BY purchase_date 
        RANGE BETWEEN INTERVAL '29 days' PRECEDING AND CURRENT ROW
    ) AS rolling_30_day_revenue 
FROM fact_sales
ORDER BY purchase_date desc
limit 1






SELECT 
    SUM(TOTAL_revenue) AS ytd_revenue
FROM FACT_SALES
WHERE PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM FACT_SALES))
  AND PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM FACT_SALES)
  AND ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable');

SELECT 
    SUM(total_revenue) AS ytd_revenue
FROM fact_sales
WHERE PURCHASE_DATE >= DATE_TRUNC('year', CURRENT_DATE)
  AND PURCHASE_DATE <= CURRENT_DATE
  


SELECT SUM(s.total_revenue) AS revenue_ly
FROM fact_sales s
WHERE s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) - INTERVAL '1 year'
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '1 year'
  AND ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable');


SELECT SUM(TOTAL_REVENUE) AS WW FROM FACT_SALES 
WHERE PURCHASE_DATE >= (
 SELECT MAX(PURCHASE_DATE)  -INTERVAL '30 DAYS'
 FROM FACT_SALES)


SELECT 
    SUM(TOTAL_revenue) AS last_30_days_revenue
FROM FACT_sales
WHERE ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable') 
AND PURCHASE_DATE >= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '30 days' 
   )

SELECT SUM(TOTAL_REVENUE) FROM  FACT_SALES
WHERE ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
AND purchase_date >= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '60 days'
AND purchase_date <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '30 days'

SELECT * FROM FACT_SALES
WHERE ORDER_STATUS  = ('Canceled')


SELECT 
    SUM(TOTAL_revenue + FREIGHT_CHARGE ) AS ytd_revenue
FROM FACT_SALES
WHERE PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM FACT_SALES))
  AND PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM FACT_SALES)


SELECT SUM(TOTAL_revenue + FREIGHT_CHARGE ) AS revenue_ly
FROM fact_sales s
WHERE s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) - INTERVAL '1 year'
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '1 year'     ---GMV LAST YEAR

SELECT  COUNT( ORDER_ID)
FROM fact_sales s
WHERE s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) 
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales)      ---ITEM SOLD CURRENT YEAR




SELECT  COUNT( ORDER_ID)
FROM fact_sales s
WHERE s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) - INTERVAL '1 year'
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '1 year'     --ITEM SOLD  LAST YEAR

SELECT SUM(TOTAL_REVENUE) FROM FACT_SALES
WHERE ORDER_STATus IN ('Canceled')

SELECT SUM(TOTAL_REVENUE)
FROM fact_sales s
WHERE ORDER_STATus IN ('Canceled')
AND s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) 
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales)      ---ITEM SOLD CURRENT YEAR


SELECT SUM(TOTAL_REVENUE)
FROM fact_sales s
WHERE  ORDER_STATus IN ('Canceled')
AND s.PURCHASE_DATE >= DATE_TRUNC('year', (SELECT MAX(PURCHASE_DATE) FROM fact_sales)) - INTERVAL '1 year'
  AND s.PURCHASE_DATE <= (SELECT MAX(PURCHASE_DATE) FROM fact_sales) - INTERVAL '1 year'



WITH customer_first_purchase AS (
    SELECT
        customer_UNIQUE_id,
        MIN(purchase_date)::date AS first_purchase_date
    FROM FACT_SALES
    GROUP BY customer_UNIQUE_id
),

customer_yearly_purchase AS (
    SELECT DISTINCT
        customer_UNIQUE_id,
        EXTRACT(YEAR FROM purchase_date)::int AS purchase_year
    FROM FACT_SALES
)

SELECT
    cyp.purchase_year,

    COUNT(DISTINCT CASE
        WHEN EXTRACT(YEAR FROM cfp.first_purchase_date)::int = cyp.purchase_year
        THEN cyp.customer_UNIQUE_id
    END) AS new_customers,

    COUNT(DISTINCT CASE
        WHEN EXTRACT(YEAR FROM cfp.first_purchase_date)::int < cyp.purchase_year
        THEN cyp.customer_UNIQUE_id
    END) AS repeat_customers,

    COUNT(DISTINCT cyp.customer_UNIQUE_id) AS total_customers

FROM customer_yearly_purchase cyp
JOIN customer_first_purchase cfp
    ON cyp.customer_UNIQUE_id = cfp.customer_UNIQUE_id

GROUP BY cyp.purchase_year
ORDER BY cyp.purchase_year;

