SET SEARCH_PATH TO E_COMMERCE, ECOMMERCE;

SELECT (SUM(TOTAL_REVENUE) /  COUNT(DISTINCT ORDER_ID), 2 ) AS AOV 
FROM FACT_SALES 
WHERE ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable');      -- CHECKING CURRENT AOV


SELECT (SUM(TOTAL_REVENUE) /  COUNT(DISTINCT ORDER_ID), 2 ) AS AOV 
FROM FACT_SALES 
WHERE ORDER_STATUS IN ('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
AND purchase_date >= DATE '2017-01-01'
AND purchase_date < DATE '2018-01-01';                                                               -- CHECKING CURRENT AOV FOR LAST YEAR 


-- VALIDATING  YTD  LY REVENUE AND  GROWTH

WITH MAX_DATE_CTE AS (
SELECT MAX(PURCHASE_DATE) AS MAX_DATE
FROM FACT_SALES
),

REVENUE_CTE AS (SELECT 
SUM(TOTAL_REVENUE) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND PURCHASE_DATE < M.MAX_DATE
) AS YTD_REVENUE,

SUM(TOTAL_REVENUE) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) - INTERVAL '1 YEAR'
AND PURCHASE_DATE < DATE_TRUNC('YEAR', M.MAX_DATE)
) AS LY_REVENUE

FROM FACT_SALES FS
CROSS JOIN MAX_DATE_CTE M
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')

)

SELECT 
(YTD_REVENUE - LY_REVENUE)  / (LY_REVENUE) * 100 AS GROWTH_PERCENTAGE ,
YTD_REVENUE,
LY_REVENUE
FROM REVENUE_CTE;




-- VALIDATING  REVENUE FOR LAST 30 AND  60 DAYS  

WITH MAX_DATE_CTE  AS 
(SELECT MAX(PURCHASE_DATE) AS  MAX_DATE  
FROM FACT_SALES
),

REVENUE as (SELECT 
SUM(TOTAL_REVENUE) FILTER(
WHERE PURCHASE_DATE >= M.MAX_DATE -INTERVAL '30 DAYS'
AND PURCHASE_DATE < M.MAX_DATE) 
AS THIRTY_DAYS,

SUM(TOTAL_REVENUE) FILTER (
WHERE PURCHASE_DATE >= M.MAX_DATE -INTERVAL '60 DAYS'
AND PURCHASE_DATE <= M.MAX_DATE -INTERVAL '30 DAYS')
AS SIXTY_DAYS


FROM FACT_SALES FS 
CROSS JOIN MAX_DATE_CTE M 
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
)
SELECT 
ROUND((THIRTY_DAYS - SIXTY_DAYS) / SIXTY_DAYS * 100, 2) AS  GROWTH,
THIRTY_DAYS,
SIXTY_DAYS
FROM REVENUE


--- VALIDATING  GMV


WITH MAX_DATE_CTE  AS 
(SELECT MAX(PURCHASE_DATE) AS  MAX_DATE  
FROM FACT_SALES
),

GMV AS (SELECT 
SUM(TOTAL_REVENUE + FREIGHT_CHARGE) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND PURCHASE_DATE <= M.MAX_DATE
) AS YTD_GMV,

SUM(TOTAL_REVENUE + FREIGHT_CHARGE)  FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) - INTERVAL ' 1 YEAR'
AND PURCHASE_DATE <= DATE_TRUNC('YEAR', M.MAX_DATE) 
) AS LY_GMV

FROM FACT_SALES FS 
CROSS JOIN MAX_DATE_CTE M 
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
)
SELECT 
ROUND((YTD_GMV - LY_GMV) / LY_GMV * 100, 2) AS  GROWTH,
ROUND(YTD_GMV / 1000000, 2) AS YTD_GMV,
ROUND(LY_GMV / 1000000, 2) AS LY_GMV
FROM GMV


-- VALIDATING  ITEM SOLD 

WITH MAX_DATE_CTE AS 
(SELECT MAX(PURCHASE_DATE) AS MAX_DATE FROM FACT_SALES
),

ITEM_SOLD AS (SELECT COUNT(ORDER_ID) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE)
AND PURCHASE_DATE <= M.MAX_DATE
) AS CURRENT_ITEM_SOLD,

COUNT(ORDER_ID) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) -INTERVAL '1 YEAR'
AND PURCHASE_DATE <= DATE_TRUNC('YEAR', M.MAX_DATE)
) AS LY_ITEM_SOLD

FROM FACT_SALES FS 
CROSS JOIN MAX_DATE_CTE M
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
)
SELECT 
  ROUND((CURRENT_ITEM_SOLD - LY_ITEM_SOLD)::NUMERIC / NULLIF(LY_ITEM_SOLD, 0 ) * 100, 2 ) AS GROWTH,
CURRENT_ITEM_SOLD ,
LY_ITEM_SOLD
FROM ITEM_SOLD

SELECT * FROM FACT_SALES
-- validating  avg rating 

WITH MAX_DATE_CTE AS 
(SELECT MAX(PURCHASE_DATE) AS MAX_DATE 
FROM FACT_SALES
),
AVG AS (SELECT
AVG(REVIEW_SCORE) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) 
AND PURCHASE_DATE <= M.MAX_DATE) AS CURRENT_RATING,

AVG(REVIEW_SCORE) FILTER(
WHERE PURCHASE_DATE >= DATE_TRUNC('YEAR', M.MAX_DATE) - INTERVAL '1 YEAR'
AND PURCHASE_DATE <= DATE_TRUNC('YEAR', M.MAX_DATE)) AS PRV_RATING

FROM FACT_SALES FS
CROSS JOIN MAX_DATE_CTE M
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')
)
SELECT 
ROUND((CURRENT_RATING - PRV_RATING ) / PRV_RATING * 100, 2) AS GROWTH,
CURRENT_RATING,
PRV_RATING
FROM AVG;

-- VALIDATING  YTD AND  LY REVENUE CHART 

WITH MONTH AS 
(SELECT 
EXTRACT(MONTH FROM PURCHASE_DATE ) AS  MONTH_NO,
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
TO_CHAR(PURCHASE_DATE, 'MONTH') AS MONTH_NAME,
ROUND(SUM(TOTAL_REVENUE)::NUMERIC, 2) AS  CURRENT_YEAR
FROM FACT_SALES
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')

GROUP BY 
MONTH_NO,
MONTH_NAME,
YEAR_NO)
SELECT * FROM MONTH
WHERE YEAR_NO  = '2018'

-- VAILIDATING  AOV  MONTH CHART 

WITH MONTH AS 
(SELECT 
EXTRACT(MONTH FROM PURCHASE_DATE ) AS  MONTH_NO,
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
TO_CHAR(PURCHASE_DATE, 'MONTH') AS MONTH_NAME,
ROUND(SUM(TOTAL_REVENUE) / COUNT( DISTINCT ORDER_ID ), 2) AS  CURRENT_YEAR
FROM FACT_SALES
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')

GROUP BY 
MONTH_NO,
MONTH_NAME,
YEAR_NO)
SELECT * FROM MONTH
WHERE YEAR_NO  = '2018'


-- VAILIDATING  ITEM SOLD  BY  PRODUCT  CATEGORY 

WITH ITEM_SOLD  AS 
(SELECT 
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
CATEGORY_GROUP,
COUNT(  ORDER_ID)
FROM FACT_SALES 
GROUP BY CATEGORY_GROUP, YEAR_NO
)
SELECT * FROM ITEM_SOLD
WHERE YEAR_NO = '2018'

-- VAILIDATING  PRODUCT CATEGORY BY REVENUE


WITH ITEM_SOLD  AS 
(SELECT 
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
CATEGORY_GROUP,
SUM(TOTAL_REVENUE)
FROM FACT_SALES 
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')

GROUP BY CATEGORY_GROUP, YEAR_NO
)
SELECT * FROM ITEM_SOLD
WHERE YEAR_NO = '2018'

SELECT * FROM FACT_SALES


WITH ITEM_SOLD  AS 
(SELECT 
EXTRACT(YEAR FROM PURCHASE_DATE) AS YEAR_NO,
CUSTOMER_STATE,
SUM(TOTAL_REVENUE) AS REVENUE
FROM FACT_SALES 
WHERE ORDER_STATUS IN 
('Approved','Delivered','Invoiced','Processing','Shipped','Unavailable')

GROUP BY  YEAR_NO, CUSTOMER_STATE
)
SELECT * FROM ITEM_SOLD
WHERE YEAR_NO = '2018'
ORDER BY REVENUE DESC










